parameters:
  # Channel list for notifications.
  # To disable or enable a channel, set true or false.
  app.notification.providers:
      email:
          symfony_mailer: { enabled: true, priority: 50, class: App\Notification\Domain\Service\Provider\Implementation\EmailNotifier }
      sms:
          twilio: { enabled: true, priority: 100, class: App\Notification\Domain\Service\Provider\Implementation\TwilioSmsNotifier }
          dummy_sms: { enabled: true, priority: 50, class: App\Notification\Domain\Service\Provider\Implementation\SMSNotifier }
      log:
          main_log: { enabled: true, priority: 100, class: App\Notification\Domain\Service\Provider\Implementation\LogNotifier }
