framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
                    service: null
            failed:
                dsn: 'doctrine://default?queue_name=failed'

        routing:
            'App\Notification\Application\Notification\NotificationInterface': async

when@test:
  framework:
      messenger:
          transports:
              # replace with your transport name here (e.g., my_transport: 'in-memory://')
              # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
              async: 'in-memory://'
